package demos:canvas-pixels;

world canvas-pixels {
  resource document {
    body: func() -> option<html-element>;
    create-element: func(local-name: string) -> element;
  }
  resource canvas-rendering-context2d {
    fill-rect: func(x: f64, y: f64, width: f64, height: f64);
    get-image-data: func(x: f64, y: f64, width: f64, height: f64) -> list<u8>;
    put-image-data: func(data: list<u8>, x: f64, y: f64, width: f64, height: f64);
    set-fill-style: func(value: string);
  }
  resource element {
    append-child: func(child: borrow<element>) -> element;
    get-context2d: func() -> canvas-rendering-context2d;
    set-attribute: func(qualified-name: string, value: string);
    text-content: func(value: string);
  }
  resource html-element {
    append-child: func(child: borrow<element>) -> element;
  }
  resource window {
    document: func() -> document;
  }

  import get-window: func() -> window;
  import now: func() -> f64;

  export run: func(size: u32, min-ms: u32);
}
