package demos:todomvc;

world todomvc {
  resource document {
    get-body: func() -> option<html-element>;
    create-element: func(local-name: string) -> element;
    create-text-node: func(data: string) -> text;
  }
  resource element {
    append-child: func(node: borrow<node>) -> node;
    set-attribute: func(qualified-name: string, value: string);
    set-text-content: func(value: string);
  }
  resource html-element {
    append-child: func(node: borrow<node>) -> node;
  }
  resource node {
  }
  resource text {
  }
  resource window {
    get-document: func() -> document;
  }

  import get-window: func() -> window;

  import element-as-node: func(v: borrow<element>) -> node;
  import text-as-node: func(v: borrow<text>) -> node;

  export run: func();
}
