#!/usr/bin/env bash
#
# I apologize for the ridiculous hack that follows. Claude wrote it in order to
# work around a stupid bug in the C++ bindings generator. I look forward to
# deleting all of this.
# -Ben
#
# unwitting-bindgen.sh — a drop-in replacement for `wit-bindgen cpp` that keeps
# the emitted component FLAT (no component/instance sections), which our Firefox
# component runtime requires.
#
# The problem: wit-bindgen's `cpp` generator only emits idiomatic resource
# *methods* for resources declared inside an `interface`. But an interface import
# compiles to a component-instance section our runtime can't parse; it needs
# flat, world-scoped (root-level) imports. So we can't just write the WIT either
# way and be done.
#
# The hack, hidden here so example build scripts stay simple:
#   1. Take a single WORLD-scoped source WIT (flat imports).
#   2. Rewrite its resources + free functions into an `interface dom`, leaving a
#      world that `import dom` / re-exports — purely to feed the `cpp` generator.
#   3. Run `wit-bindgen cpp` on that to get idiomatic C++ bindings.
#   4. Retarget the generated import thunks from the `<pkg>/dom` module back to
#      the flat `$root` module.
#   5. Replace the (interface-scoped) component type with a world-scoped one
#      generated from the ORIGINAL source WIT.
# The output dir then looks just like a normal flat `cpp` binding: a header, a
# <world>.cpp, and a <world>_component_type.o the caller compiles and links.
#
# Usage: unwitting-bindgen.sh <wit-dir-or-file> --out-dir <dir>
#   (mirrors `wit-bindgen cpp <wit> --out-dir <dir>`)

set -euo pipefail

src=""
out=""
while [ $# -gt 0 ]; do
  case "$1" in
    --out-dir) out="$2"; shift 2 ;;
    *) src="$1"; shift ;;
  esac
done
if [ -z "$src" ] || [ -z "$out" ]; then
  echo "usage: unwitting-bindgen.sh <wit-dir-or-file> --out-dir <dir>" >&2
  exit 2
fi

# Resolve the single source .wit (a dir with one .wit, or a file path).
if [ -d "$src" ]; then
  witfile=$(ls "$src"/*.wit | head -1)
else
  witfile="$src"
fi

pkg=$(sed -n 's/^package[[:space:]]\{1,\}\([^;]*\);.*/\1/p' "$witfile" | head -1)
world=$(sed -n 's/^world[[:space:]]\{1,\}\([A-Za-z0-9_-]\{1,\}\).*/\1/p' "$witfile" | head -1)
world_id=$(printf '%s' "$world" | tr '-' '_')
iface="dom"

if [ -z "$pkg" ] || [ -z "$world" ]; then
  echo "unwitting-bindgen: could not parse package/world from $witfile" >&2
  exit 1
fi

rm -rf "$out"
mkdir -p "$out/_iface/wit" "$out/_ctype"

# 1-2. Rewrite the world's resources + free functions into `interface dom`,
# leaving the world importing that interface. Everything at world scope goes into
# the interface except `export` items (world-level func imports lose the leading
# `import` keyword). Brace depth tells us where the world body ends.
awk -v pkg="$pkg" -v world="$world" -v iface="$iface" '
  # Count matches of a string pattern (passed as a string, not a /regex/, so awk
  # does not evaluate it against $0 before the call). Uses a temp so $0 is intact.
  function count(s, pat,   t) { t = s; return gsub(pat, "&", t) }
  BEGIN { inworld = 0; depth = 0; nif = 0; nw = 0 }
  !inworld && $0 ~ /^[[:space:]]*world[[:space:]]/ { inworld = 1; depth = 1; next }
  inworld {
    cur = depth
    depth = depth + count($0, "[{]") - count($0, "[}]")
    if (cur == 1 && depth == 0) next                       # the world-closing }
    if (cur == 1 && $0 ~ /^[[:space:]]*export[[:space:]]/) { wbuf[nw++] = $0; next }
    if (cur == 1 && $0 ~ /^[[:space:]]*import[[:space:]]+[A-Za-z0-9_-]+[[:space:]]*:/) {
      s = $0; sub(/^[[:space:]]*import[[:space:]]+/, "  ", s); ibuf[nif++] = s; next
    }
    ibuf[nif++] = $0                                       # resources, types, etc.
    next
  }
  END {
    print "// GENERATED by unwitting-bindgen.sh from the world-scoped source WIT."
    print "// Do not edit. Interface wrapper exists only to coax methods out of"
    print "// wit-bindgen cpp; imports are flattened back to $root after generation."
    print "package " pkg ";"
    print ""
    print "interface " iface " {"
    for (i = 0; i < nif; i++) print ibuf[i]
    print "}"
    print ""
    print "world " world " {"
    print "  import " iface ";"
    print ""
    for (i = 0; i < nw; i++) print wbuf[i]
    print "}"
  }
' "$witfile" > "$out/_iface/wit/world.wit"

# 3. Idiomatic C++ bindings from the interface-wrapped WIT.
wit-bindgen cpp "$out/_iface/wit" --out-dir "$out"

# 4. Retarget the import module: <pkg>/dom -> $root, matching a flat component.
perl -i -pe 's{import_module\("'"$pkg"'/'"$iface"'"\)}{import_module("\$root")}g' \
  "$out/${world_id}.cpp"

# 5. Swap in a world-scoped component type (from the ORIGINAL flat WIT), so the
# linked component declares flat root imports rather than an interface instance.
wit-bindgen c "$src" --out-dir "$out/_ctype" >/dev/null
cp "$out/_ctype/${world_id}_component_type.o" "$out/${world_id}_component_type.o"
