package demos:dom-traversal;

world dom-traversal {
  resource document {
    body: func() -> option<html-element>;
    create-element: func(local-name: string) -> element;
  }
  resource element {
    append-child: func(child: borrow<element>) -> element;
    first-child: func() -> option<element>;
    next-sibling: func() -> option<element>;
    text-content: func(value: string);
  }
  resource html-element {
    append-child: func(child: borrow<element>) -> element;
  }
  resource window {
    document: func() -> document;
  }

  import get-window: func() -> window;
  import now: func() -> f64;

  export run: func(node-count: u32, iterations: u32);
}
