package demos:string-marshalling;

world string-marshalling {
  resource document {
    body: func() -> option<html-element>;
    create-element: func(local-name: string) -> element;
  }
  resource element {
    append-child: func(node: borrow<node>) -> node;
    text-content: func() -> string;
    set-text-content: func(value: string);
  }
  resource html-element {
    append-child: func(node: borrow<node>) -> node;
  }
  resource node {
  }
  resource window {
    document: func() -> document;
  }

  import element-as-node: func(v: borrow<element>) -> node;
  import get-window: func() -> window;
  import now: func() -> f64;

  export run: func(min-ms: u32);
}
