package demos:attribute-churn;

world attribute-churn {
  resource document {
    body: func() -> option<html-element>;
    create-element: func(local-name: string) -> element;
  }
  resource element {
    append-child: func(node: borrow<node>) -> node;
    set-attribute: func(qualified-name: string, value: trusted-type-or-string);
    set-attributes: func(pairs: list<tuple<string, string>>);
    set-text-content: func(value: string);
  }
  resource html-element {
    append-child: func(node: borrow<node>) -> node;
  }
  resource node {
  }
  resource trusted-html {
  }
  variant trusted-html-or-trusted-script-or-trusted-script-url {
    trusted-html(trusted-html),
    trusted-script(trusted-script),
    trusted-script-url(trusted-script-url),
  }
  resource trusted-script {
  }
  resource trusted-script-url {
  }
  type trusted-type = trusted-html-or-trusted-script-or-trusted-script-url;
  variant trusted-type-or-string {
    trusted-type(trusted-type),
    %string(string),
  }
  resource window {
    document: func() -> document;
  }

  import element-as-node: func(v: borrow<element>) -> node;
  import get-window: func() -> window;
  import now: func() -> f64;

  export run: func(elements: u32, frames: u32);
}
